LIST_IMAGES_PATH = "Images/"
LIST_SOUNDS_PATH = "Sounds/"

WIDTH_OF_WIN = 300
HEIGHT_OF_WIN = 300

WIDTH_OF_SECOND_MAIN_FRAME = WIDTH_OF_WIN/2
HEIGHT_OF_TEXT_FRAME = HEIGHT_OF_WIN/2
WIDTH_OF_IMAGE_FRAME = WIDTH_OF_WIN/2
WIDTH_OF_OPTION_FRAME = WIDTH_OF_WIN/2

BACKGROUND_COLOR = "#323033"
BACKGROUND_COLOR_OPTIONS = 'white'
BORDER_COLOR = "#514E52"
BORDER_TICKNESS = 3

MIN_MINUTE_TO_WAIT = 1
MAX_MINUTE_TO_WAIT = 8

FONT = ("Impact", 30)
COLOR_TEXT = 'white'